
name: Update README

on:
  schedule:
    - cron: "*/60 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Readme-Workflows/recent-activity@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          CONFIG_FILE: "./.github/update-readme.config.yml"

      - uses: actions-js/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "master"

      - uses: actions/checkout@v2
      - uses: DenverCoderOne/github-activity-readme@commit-username-and-email
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
