name: Waka Readme

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: "*/60 * * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          BLOCKS: .■
          TIME_RANGE: last_7_days
          SHOW_TIME: false
          SHOW_MASKED_TIME: true
          LANG_COUNT: 10
          
          INPUT_SHOW_TIMEZONE: True
          INPUT_SHOW_PROJECTS: True
          INPUT_SHOW_EDITORS: True
          INPUT_SHOW_OS: True
          INPUT_SHOW_LANGUAGE: True
          INPUT_SYMBOL_VERSION: 1
          INPUT_SHOW_LINES_OF_CODE: True
          INPUT_SHOW_LOC_CHART: True
          INPUT_SHOW_PROFILE_VIEWS: True
          INPUT_SHOW_TOTAL_CODE_TIME: True
          INPUT_SHOW_SHORT_INFO: True
          INPUT_SHOW_COMMIT: True
          INPUT_SHOW_DAYS_OF_WEEK: True
          INPUT_SHOW_LANGUAGE_PER_REPO: True
          INPUT_SHOW_UPDATED_DATE: True
          INPUT_COMMIT_BY_ME: True
